FROM oven/bun:1

WORKDIR /usr/src/app

COPY package.json package.json
COPY turbo.json turbo.json

COPY apps/web apps/web

RUN bun install
RUN bun run db:generate

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

RUN bun run build

EXPOSE 3000

CMD ["bun", "run", "start:web"]
